"""Manifest contracts and safe fixture loading helpers."""

from .contracts import (
    AssetRecord,
    BenchmarkLabel,
    BenchmarkPairRecord,
    EvidenceKind,
    EvidenceRecord,
    EvidenceState,
    FigureRecord,
    FixtureManifest,
    FunctionalAssertionRecord,
    FunctionalSlot,
    LicenseStatus,
    NormalizedBBox,
    PageRecord,
    RegionRecord,
    RelationPredicate,
    RelationRecord,
    SourceRecord,
    TextChunkRecord,
    TextKind,
    ValidatedFixture,
)
from .loader import (
    DEFAULT_MAX_ASSET_BYTES,
    ManifestValidationError,
    load_manifest,
    parse_manifest,
    resolve_contained_path,
    validate_assets,
    validate_manifest_name,
)

__all__ = [
    "AssetRecord",
    "BenchmarkLabel",
    "BenchmarkPairRecord",
    "EvidenceKind",
    "EvidenceRecord",
    "EvidenceState",
    "FixtureManifest",
    "FigureRecord",
    "FunctionalAssertionRecord",
    "FunctionalSlot",
    "LicenseStatus",
    "NormalizedBBox",
    "PageRecord",
    "RelationPredicate",
    "RelationRecord",
    "RegionRecord",
    "SourceRecord",
    "TextChunkRecord",
    "TextKind",
    "ValidatedFixture",
    "DEFAULT_MAX_ASSET_BYTES",
    "ManifestValidationError",
    "load_manifest",
    "parse_manifest",
    "resolve_contained_path",
    "validate_assets",
    "validate_manifest_name",
]
